### ISSUE TITLE
Doesn't work in El Capitan

### ISSUE THREAD

**Issue by wilsonwc** [sampayo/Alfred-WorkFlows#3]
The input/output options don't seem to populate since I switched to El Capitan

**Comment by wilsonwc** [comment]
Sorry about this, I started looking at the script and realized that Alfred was not enabled to control my computer in the accessability features.  All is working now

**Comment by carolineschnapp** [comment]
And how did you make it work exactly, @wilsonwc ?

**Comment by carolineschnapp** [comment]
I found the answer here: https://github.com/sampayo/Alfred-WorkFlows/issues/1#issuecomment-31214177 thank you, sorry!
